//! Motion-based raymarching using GPU-generated rays
//!
//! This module processes rays generated by the GPU motion detection pipeline.
//! The GPU compute shaders handle:
//! 1. Frame differencing (current vs previous frame)
//! 2. Ray generation for motion pixels
//!
//! This module then:
//! 1. Reads rays from the GPU buffer (via readback)
//! 2. Raymarches each ray through the voxel grid
//! 3. Accumulates voxel contributions for detection/tracking

use bevy::prelude::*;
use glam::UVec3;
use std::collections::HashMap;

use iluvatar_core::VoxelContribution;

use crate::gpu_pipeline::RayBufferResource;
use crate::voxels::{SimulatorConfig, SimulatorRaymarcher, VoxelGridResource};

/// Plugin for motion-based raymarching
pub struct MotionRaymarchPlugin;

impl Plugin for MotionRaymarchPlugin {
    fn build(&self, app: &mut App) {
        // motion_based_raymarch runs in Update, consuming rays from GPU readback
        // The readback happens asynchronously, so rays are available 1-2 frames later
        app.add_systems(
            Update,
            motion_based_raymarch.before(crate::voxels::decay_voxels),
        );
    }
}

/// Raymarch from rays generated by GPU motion detection
///
/// This consumes rays from `RayBufferResource` (populated by GPU readback)
/// and marches them through the voxel grid.
pub fn motion_based_raymarch(
    mut grid_res: ResMut<VoxelGridResource>,
    sim_config: Res<SimulatorConfig>,
    tracking_config: Option<Res<crate::tracking::TrackingConfig>>,
    mut ray_buffer: ResMut<RayBufferResource>,
) {
    // Copy config values we need for raymarching to avoid borrow conflicts
    let raymarch_config = grid_res.config.clone();
    let bounds = grid_res.bounds;
    let voxel_size = sim_config.voxel_size;
    let grid_dims = sim_config.grid_dimensions;

    // Clear the grid if configured to do so (frame-by-frame mode)
    let should_clear = tracking_config
        .as_ref()
        .map(|c| c.clear_grid_each_frame)
        .unwrap_or(false);

    if should_clear {
        grid_res.grid.clear();
    }

    // Reset stats
    grid_res.rays_cast = 0;
    grid_res.voxels_contributed = 0;

    // Check if we have any rays to process
    if ray_buffer.pending_rays.is_empty() {
        return;
    }

    // Create raymarcher
    let raymarcher = SimulatorRaymarcher::new(&raymarch_config, &bounds, voxel_size);

    // Group rays by camera for batch processing
    let mut contributions_by_camera: HashMap<u64, HashMap<(u32, u32, u32), f32>> = HashMap::new();

    // Process all rays from GPU buffer
    for (camera_id, ray) in ray_buffer.pending_rays.drain(..) {
        let camera_key = u64::from(camera_id % 64);

        let contributions = contributions_by_camera.entry(camera_key).or_default();

        raymarcher.march_ray(&ray, grid_dims, contributions);
        grid_res.rays_cast += 1;
    }

    // Add contributions to the voxel grid
    for (camera_id, contributions) in contributions_by_camera {
        let voxel_contributions: Vec<VoxelContribution> = contributions
            .into_iter()
            .map(|((x, y, z), intensity)| VoxelContribution {
                index: UVec3::new(x, y, z),
                intensity,
            })
            .collect();

        grid_res.voxels_contributed += voxel_contributions.len() as u32;

        // Add contributions to the real SparseVoxelGrid with camera tracking
        grid_res
            .grid
            .add_camera_contributions(camera_id, &voxel_contributions);
    }

    if grid_res.rays_cast > 0 {
        debug!(
            "Processed {} rays, {} voxel contributions",
            grid_res.rays_cast, grid_res.voxels_contributed
        );
    }
}
